export default [
  {
    id: 1,
    name: "Herederos del Marques de Riscal Sauvignon DO, 0.75 л",
    imgSrc: "wine1.png",
    price: 2601,
    salePrice: 2890,
    category: "wine",
    parameters: {
      country: "Испания",
      type: "Белое",
      toxicity: "13%",
      volume: "0.75 л",
    },
  },
  {
    id: 2,
    name: "Domaine de l'Horizon, Mar y Muntanya IGP, 2018",
    imgSrc: "wine2.png",
    price: 2974,
    salePrice: 3718,
    category: "wine",
    parameters: {
      country: "Франция",
      type: "Сухое",
      toxicity: "12.5%",
      volume: "0.75 л",
    },
  },
  {
    id: 3,
    name: "Вино Гевюрцтраминер  бел. п/сл. 0,75л. 12,5%",
    imgSrc: "wine3.png",
    price: 3137,
    salePrice: 3485,
    category: "wine",
    parameters: {
      country: "Франция",
      type: "Полусладкое",
      toxicity: "12.5%",
      volume: "0.75 л",
    },
  },
  {
    id: 4,
    name: "Charles Simon Brut Supreme, 0.75 л",
    imgSrc: "champagne1.png",
    price: 3690,
    salePrice: 4100,
    category: "champagne",
    parameters: {
      country: "Франция",
      type: "Сухое",
      toxicity: "12%",
      volume: "0.75 л",
    },
  },
  {
    id: 5,
    name: "Masachs, Cava Brut",
    imgSrc: "champagne2.png",
    price: 1395,
    salePrice: 1550,
    category: "champagne",
    parameters: {
      country: "Испания",
      type: "Игристое",
      toxicity: "11.5%",
      volume: "0.75 л",
    },
  },
  {
    id: 6,
    name: "Reguta, Falconello Ribolla Gialla Brut, 0.75 л",
    imgSrc: "champagne3.png",
    price: 851,
    salePrice: 945,
    category: "champagne",
    parameters: {
      country: "Италия",
      type: "Игристое",
      toxicity: "12%",
      volume: "0.75 л",
    },
  },
  {
    id: 7,
    name: "Neft, black barrel, 0.7 л",
    imgSrc: "strong1.png",
    price: 3600,
    salePrice: 6000,
    category: "strong",
    parameters: {
      country: "Австрия",
      type: "Классическая",
      toxicity: "40%",
      volume: "0.7 л",
    },
  },
  {
    id: 8,
    name: "Прасковейский Ставрополь КВ, 0.5 л",
    imgSrc: "strong2.png",
    price: 1816,
    salePrice: 2270,
    category: "strong",
    parameters: {
      country: "Россия",
      type: "Более 5 лет",
      toxicity: "40%",
      volume: "0.5 л",
    },
  },
  {
    id: 9,
    name: "Tatratea Coconut, 0.7 л",
    imgSrc: "strong3.png",
    price: 2745,
    salePrice: 3050,
    category: "strong",
    parameters: {
      country: "Словакия",
      type: "Чайный",
      toxicity: "22%",
      volume: "0.7 л",
    },
  },
  {
    id: 10,
    name: "Corona Extra, 0.355 л",
    imgSrc: "beer1.png",
    price: 154,
    salePrice: 220,
    category: "beer",
    parameters: {
      country: "Мексика",
      type: "Светлое",
      toxicity: "4.5%",
      volume: "0.355 л",
    },
  },
  {
    id: 11,
    name: "Tuborg Green, 0.48 л",
    imgSrc: "beer2.png",
    price: 110,
    salePrice: null,
    category: "beer",
    parameters: {
      country: "Россия",
      type: "Светлое",
      toxicity: "4.6%",
      volume: "0.48 л",
    },
  },
  {
    id: 12,
    name: "Пиво Леффе Блонд 0,33л. 6,6%",
    imgSrc: "beer3.png",
    price: 235,
    salePrice: null,
    category: "beer",
    parameters: {
      country: "Бельгия",
      type: "Светлое",
      toxicity: "6.6%",
      volume: "0.33 л",
    },
  },
];
